---
name: 'RightClickFarming'
main: 'me.raddari.rcf.RightClickFarming'
version: '1.0.1'
description: 'Allows players to farm by right clicking'
author: 'Raddari'
website: 'https://github.com/Raddari/RightClickFarming'
api-version: '1.16'
...
